spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
mybatis:
    typeAliasesPackage: cn.*.dao
    mapperLocations: classpath:/mappers/*.xml
    configLocation: classpath:/mybatis-config.xml
server:
  port: 8080
  context-path: /hyrz/
